[Agilent]
git-tree-sha1 = "19bcd4ecdc2ac5fb3604ef71f3fa019a378c3218"

    [[Agilent.download]]
    url = "https://raw.githubusercontent.com/oniehuis/JuChrom-ExampleData/main/Agilent.tar.gz"
    sha256 = "7be6740d83ae1f6e158921e24d1f6fa2865eaba9f8d27c9f24220cd48e119c9f"

[ANDI]
git-tree-sha1 = "fbb1cfc928d393c7b88470d38380a57185f7973f"

    [[ANDI.download]]
    url = "https://raw.githubusercontent.com/oniehuis/JuChrom-ExampleData/main/ANDI.tar.gz"
    sha256 = "fc781115eadba07853c2030fe64300d5569492e7cfa04374d4ab3e3edeb8d192"

[calibration]
git-tree-sha1 = "f60cfd441c6aeb9f95c44b6fe167e74af1ed88e8"

    [[calibration.download]]
    url = "https://raw.githubusercontent.com/oniehuis/JuChrom-ExampleData/main/calibration.tar.gz"
    sha256 = "a99d0b2dda43541ff81f8e35a927e7d78107c2839bdd26d448e3acb2deb856ea"