name = "JuChrom"
uuid = "401750c1-7610-466c-a8c0-dbc4483c7f4e"
authors = ["Oliver Niehuis <oliver.niehuis@gmail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
julia = "1.10"
Reexport = "v1.2.2"
Unitful = "v1.21.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
