name = "JuChrom"
uuid = "401750c1-7610-466c-a8c0-dbc4483c7f4e"
authors = ["Oliver Niehuis <oliver.niehuis@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
