name: CompatHelper

on:
  schedule:
    - cron: '0 3 * * 1'
  workflow_dispatch:

jobs:
  compat:
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/CompatHelper@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
